Fix Jenkinsfile OWASP stage

diff --git a/jenkins/Jenkinsfile b/jenkins/Jenkinsfile
--- a/jenkins/Jenkinsfile
+++ b/jenkins/Jenkinsfile
@@ -1,43 +1,51 @@
 pipeline {
     agent any
+
     stages {
-        stage('Clone Repo') {
+        stage("Clone Repo") {
             steps {
-                git branch: 'main', url: 'https://github.com/L1bun/devsecops-pipeline.git'
+                git branch: "main", url: "https://github.com/L1bun/devsecops-pipeline.git"
             }
         }
-        stage('Build Docker Image') {
+
+        stage("Build Docker Image") {
             steps {
-                sh 'docker build -t devsecops-app ./app'
+                sh "docker build -t devsecops-app ./app"
             }
         }
-        stage('OWASP Security Scan') {
+
+        stage("OWASP Security Scan") {
             steps {
                 sh '''
-                    docker run --rm \
-                    -v $(pwd):/src \
+                    mkdir -p security-report
+
+                    docker run --rm -v $(pwd):/src \
                     owasp/dependency-check \
                     --scan /src \
                     --format HTML \
-                    --out /src/security-report
+                    --out /src/security-report || true
                 '''
             }
         }
-        stage('Run Container') {
+
+        stage("Run Container") {
             steps {
-                sh 'docker run -d -p 5000:5000 devsecops-app'
+                sh "docker stop devsecops-app || true"
+                sh "docker rm devsecops-app || true"
+                sh "docker run -d -p 5000:5000 --name devsecops-app devsecops-app"
             }
         }
     }
+
     post {
         always {
-            echo 'Pipeline completed!'
+            echo "Pipeline completed!"
         }
         success {
-            echo 'Build succeeded!'
+            echo "Build successful!"
         }
         failure {
-            echo 'Build failed!'
+            echo "Build failed!"
         }
     }
 }
